"""виправлено граматичні помилки в таблицях

Revision ID: 1e6d3c104004
Revises: 
Create Date: 2024-11-06 17:03:07.087408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e6d3c104004'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('unique_members_count', sa.Integer(), nullable=True))
    op.drop_column('groups', 'unique_mebmer_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('unique_mebmer_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('groups', 'unique_members_count')
    # ### end Alembic commands ###
