"""оновленно структуру бд

Revision ID: 38a11d83afa2
Revises: 88fb1ce5bc6f
Create Date: 2024-11-13 18:32:12.248351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38a11d83afa2'
down_revision: Union[str, None] = '88fb1ce5bc6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_groups_group_id_fkey', 'user_groups', type_='foreignkey')
    op.create_foreign_key(None, 'user_groups', 'groups', ['group_id'], ['group_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_groups', type_='foreignkey')
    op.create_foreign_key('user_groups_group_id_fkey', 'user_groups', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
